### ISSUE TITLE
Run?

### ISSUE THREAD

**Issue by ZZcat** [Waitsnake/AnimatedGif#1]
How do you setup and run this?
Thanks

**Comment by archagy** [comment]
im not sure but in AnimatedGif/AnimatedGif/AnimatedGifView.m in line in line 27 has the path of the gif. Maybe works changing that.

**Comment by Waitsnake** [comment]
No, in line 27 is just an initial file name that doesn't matter.
Well as long as you not select your own file the screensaver will just show an black screen.
As you can see in line 229 the file name will be overwritten by the selected file name from in the configure sheet when pressing OK. And in line 236 the new file name will be written to the plist file on your hard disk.

Here a short setup:
1.) download compiled release file here:
https://github.com/Stino/AnimatedGif/blob/master/Release/AnimatedGif.saver.zip?raw=true
2.) unzip the downloaded zip file (a double click should do in OSX)
3.) double click on the extracted "AnimatedGif.saver" file and OSX will ask if you like to install screen saver.
4.) open system preferences and there go to schreen saver preferences
5.) select the screensaver with name AnimatedGif
6.) when AnimatedGif is selected there should be an screensaver option button that you have to press
7.) in the option window press button "select file" and an file dialog should open where you select your gif file and press than "open"
8.) in the option window press "OK"  button and now your own gif file should be selected an visible in screensaver

I hope this helps. If setup is not working as I describe it here maybe it is not working on your OSX version. In this case please make a note here. I use and compile it for OSX 10.9 Mavericks and never try it on a newer version of OSX.

**Comment by shamesung** [comment]
Place in ~/Library/Screen Savers/
