### ISSUE TITLE
Feature Request: GIF files over 30 fps

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#19]
Please allow to load upto 60fps GIFs

value from gif will allow over 30fps but manual frame rate is limited to 30

![screen shot 2017-07-08 at 9 59 49 pm](https://user-images.githubusercontent.com/6269751/27990830-e0a1f314-6428-11e7-9e95-d56f791df6eb.png)

**Comment by Waitsnake** [comment]
But you know that this limit of 1 to 30 fps is only relevant if you **manual choose an fps value**?

If you **disable the manual option** the fps value **from the selected GIF is automatic used**. In this **automatic mode** there is **no limit of fps** and the Screensaver will try to change the frames in this fast frame rate as long as your hardware(CPU and GPU) and/or your operating system is able to do so.

I thought about higher values on the manual scale when I start the project, but it looks awful to have 60 strokes on this small size and it is hard the select an value.
The manual option was only intended to run to run a GIF at _slower fps_ as the unlimited automatic option does to save some CPU time. I don't saw a real use case to run it in the manual mode faster than 30 fps.

**Comment by Waitsnake** [comment]
The slider for manual selecting fps is now from 1 to 60 fps extended.
I play with the 60 fps value and it was not as bad as I remember it. 
But remember if you disable manual selecting of fps AnimatedGif uses the value of the GIF file anyway. What ever this is, maybe 70 fps.

It is changed with last commit 56.
