### ISSUE TITLE
Feature Request: GIF Overflow

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#20]
Feature to allow gif to overflow screen creating a nice full screen effect

From this:

![screen shot 2017-07-08 at 10 03 47 pm](https://user-images.githubusercontent.com/6269751/27990852-9235f4cc-6429-11e7-94c6-7bafe78f154a.png)

To this:

![screen shot 2017-07-08 at 10 04 19 pm](https://user-images.githubusercontent.com/6269751/27990853-923686f8-6429-11e7-9c82-e90f23fc7599.png)

**Comment by Waitsnake** [comment]
You mean an kind of zoom level that scales the GIF?
I will think about this...

**Comment by Waitsnake** [comment]
With the commit "Implement feature request GIF Overflow" I implement the requested feature. It will be part of next release 1.4.0 . The scaling has the values 0.1, 0.25, 0.5, 0.75, 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10.

**Comment by Waitsnake** [comment]
Added with Release 1.4.0 .
