### ISSUE TITLE
Screensaver is misaligned under the menu bar when run in background

### ISSUE THREAD

**Issue by quenz** [Waitsnake/AnimatedGif#31]
If you run the screensaver in the background, it starts just below the menu bar, and you can see the other desktop background above it, behind the menu bar. If you have a screensaver that's the same size as the display, the bottom is cut off at the bottom.

**Comment by Waitsnake** [comment]
Sorry, but it's hard for me to understand what you mean exactly?

Can you please make a screen shoot to show the problem?

And to know what version of AnimatedGif and of the operating system do you use would be helpful too.

**Comment by Waitsnake** [comment]
I take a look at it and the thing is if the background window is created to shown at full size the operating system automatically move the windows below the menu bar. So the window of the screensaver was not scaled "wrong" but a at the "wrong" position (shifted below menu bar).

By using setFrameOrigin() function I move the screensaver window upward e.g. "below" the menu bar. But you only see the content of the screensaver is moved up a litte bit. The operating system ignores the window below the menu bar and you see your background picture as transparent effect in the menu bar anyway. It seems from apple point of view it was never intended that there is any window below the menu bar and so the operating system is completely ignoring it when creating the "transparent effect". Maybe that was the reason why the operating system shifts the window position automatically a bit down in the first place?

That the drawing of the transparence effect ignores windows below the menu bar can only changed by Apple. If this was your problem, than sorry but you have to address it direct to Apple. I will release the change with the setFrameOrigin() but this will only move the window position a bit upwards.

**Comment by Waitsnake** [comment]
Ok, the Release 1.3.5 is out and in background mode of the screensaver the position is now moved upwards "below" the menu bar and so the bottom is no longer cut off and visible (but the therefore the top is cut of since it is below the menu bar).
I will close this issue and give it an "bug" label for the "wrong" window position that is now fixed with 1.3.5 and an "wontfix" for the issue with the transparency effect of the menu bar that can only changed by Apple itself.
