### ISSUE TITLE
Feature Request: No time between random gif changes

### ISSUE THREAD

**Issue by ARRiera96** [Waitsnake/AnimatedGif#36]
First off thanks for this awesome screensaver. It would be great if we had an option to not have any time between gif changes when a directory is selected.

**Comment by Waitsnake** [comment]
Thanks for your feedback. I think it is a need idea and I wonder why this was not there in the first place. ;-)
With release 1.3.8 the last value in the change interval slider has the special value "never".

**Comment by ARRiera96** [comment]
Awesome thank you so much!
