### ISSUE TITLE
[Request] Put this screensaver on the App Store

### ISSUE THREAD

**Issue by alanyee** [Waitsnake/AnimatedGif#41]
Rather than having this file run by the user from GitHub, there might be more visibility and more trust in using it from the App Store. This way, users can just uninstall via the App Store on macOS rather than additionally downloading a separate file to uninstall the screensaver.

**Comment by Waitsnake** [comment]
Unfortunately Apple wants 99 USD per year for this service and I doubt that the revenue will be high enough to get the money back.
