### ISSUE TITLE
Frame rate of gif not detected properly

### ISSUE THREAD

**Issue by dhood** [Waitsnake/AnimatedGif#5]
Noticed that for [this gif](https://lh3.googleusercontent.com/-mDPHs4dKKVDVhgCb-wf8JT0qrO_AWW28mkMnUwkiLo=s630-fcrop64=1,01fe27dcfbaee417) the frame rate is not automatically detected properly (it runs slower than it should)

(also, [this](https://github.com/Stino/AnimatedGif/blob/ab884be7385359a129b975083f95f8695485448b/AnimatedGif/Options.xib#L98) should probably say cancel instead of Abbrechen)

Love the project, thanks a lot

**Comment by Waitsnake** [comment]
You are right, your test gif is way too slow. According to Gimp the duration between frames should be 30ms. I also looked in english [Wikipedia](https://en.wikipedia.org/wiki/GIF) for GIF-Format description and than looked with an HEX-Editor into the file at offset 0x24 and 0x25 the duration for the first frame is defined as 03 00 witch stands for 3 \* 1/100 sec = 30ms.

I load the GIF-File with class NSImage from the disk and than get an NSBitmapImageRep object from it. It has an method "valueForProperty:" to read out the value for NSImageCurrentFrameDuration witch should give back an float containing duration to next frame in second. With your GIF I saw 0.1 sec = 100ms in debugger. Thats why frame rate of 33 fps drops down to 10 fps.
 I checked other GIF's, but there NSImageCurrentFrameDuration gives back an correct value (same as Gimp). So it seems a bug of the NSBitmapImageRep class.

I google for the problem and found this here on [stackoverflow](http://stackoverflow.com/questions/27094016/nsbitmapimagerep-from-duration-for-animated-gif) where someone observed the same behavior of this class. They advice there to use CGImageSourceCopyPropertiesAtIndex as workaround with gives always back the real duration. I changed the code to use this method and now it looks better.

I also translate the "Abbrechen" button to english.
