### ISSUE TITLE
Stretch keeping ratio but filling screen completely

### ISSUE THREAD

**Issue by a8vam** [Waitsnake/AnimatedGif#6]
Hi, I love **AnimatedGif**, it works by far the best with super low cpu usage. Awesome work! If I may have a small request, I'd like to see an option for keeping the gif image's ratio but filling the screen completely with some part of the image going outside the screen area. This would make it perfect for me. Thank you!

**Comment by Waitsnake** [comment]
Hi, I'm glad to hear that you like the screensaver.
With the last commit I add an new view option "stretch to smallest side" and hope this fits your needs.

**Comment by a8vam** [comment]
Perfect! Thanks so much! You did it in just two days, wow.

**Comment by Waitsnake** [comment]
"It's nothing. I had the tire (xcode) and the jack (mac). Just be comfortable. It'll be a minute." ;-)
